# Site settings  
title: "Tuan's Blog"  
description: "AI + CS + Life"  
baseurl: ""  # Leave empty unless you're hosting in a subpath  
url: "https://vltisme.github.io"  # Your GitHub Pages URL  
email: volantuan0908@gmail.com  
author: Tuan  

remote_theme: cotes2020/jekyll-theme-chirpy  
plugins:  
  - jekyll-seo-tag  
  - jekyll-sitemap  
  - jekyll-feed  
  - jekyll-remote-theme  

# Social links (update these to your own links)  
social:  
  name: "Tuan Vo Lan"  
  links:  
    - https://github.com/VLTisME  
    - https://www.linkedin.com/in/vltisme986/  
    - mailto:volantuan0908@gmail.com