name: Deploy Jekyll site to GitHub Pages  

# Trigger the workflow on every push to the default branch (e.g., 'main')  
on:  
  push:  
    branches:  
      - main  # Replace 'main' with your default branch name, if different.  

# Define the deployment job  
jobs:  
  deploy:  
    runs-on: ubuntu-latest  

    steps:  
    # Step 1: Check out the repository  
    - name: Checkout code  
      uses: actions/checkout@v3  

    # Step 2: Set up Ruby (for Jekyll)  
    - name: Set up Ruby  
      uses: ruby/setup-ruby@v1  
      with:  
        ruby-version: 3.1  # Specify a compatible Ruby version for Jekyll  

    # Step 3: Cache dependencies to speed up builds  
    - name: Cache Ruby gems  
      uses: actions/cache@v3  
      with:  
        path: vendor/bundle  
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}  
        restore-keys: |  
          ${{ runner.os }}-gems-  

    # Step 4: Install Jekyll dependencies  
    - name: Install dependencies  
      run: bundle install  

    # Step 5: Build the Jekyll site  
    - name: Build the site with Jekyll  
      run: bundle exec jekyll build  

    # Step 6: Deploy the site to GitHub Pages  
    - name: Deploy to GitHub Pages  
      uses: peaceiris/actions-gh-pages@v3  
      with:  
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication  
        publish_dir: ./_site                       # The folder containing built files  
        publish_branch: gh-pages                   # Branch to deploy to (change if needed)