name: "Build and Deploy"
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:  
  deploy:  
    runs-on: ubuntu-latest  

    steps:  
    - name: Checkout code  
      uses: actions/checkout@v4  

    - name: Set up Ruby  
      uses: ruby/setup-ruby@v1  
      with:  
        ruby-version: 3.1  

    - name: Cache dependencies  
      uses: actions/cache@v4  
      with:  
        path: vendor/bundle  
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}  
        restore-keys: |  
          ${{ runner.os }}-gems-  

    - name: Install Jekyll dependencies  
      run: bundle install  

    - name: Build the Jekyll site  
      run: bundle exec jekyll build  

    - name: Deploy to GitHub Pages  
      uses: peaceiris/actions-gh-pages@v4  
      with:  
        github_token: ${{ secrets.GITHUB_TOKEN }}  
        publish_dir: ./_site